//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.QualityControl
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оборудование.
    /// </summary>
    // *** Start programmer edit section *** (Оборудование CustomAttributes)

    // *** End programmer edit section *** (Оборудование CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОборудованиеE", new string[] {
            "Название as \'Название\'",
            "Тип as \'Тип\'",
            "Паспорт as \'Паспорт\'"})]
    [View("ОборудованиеL", new string[] {
            "Название as \'Название\'",
            "Тип as \'Тип\'",
            "Паспорт as \'Паспорт\'"})]
    public class Оборудование : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private IIS.QualityControl.ТипУстройства fТип;
        
        private string fПаспорт;
        
        // *** Start programmer edit section *** (Оборудование CustomMembers)

        // *** End programmer edit section *** (Оборудование CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Название CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Название Get start)

                // *** End programmer edit section *** (Оборудование.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Оборудование.Название Get end)

                // *** End programmer edit section *** (Оборудование.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Название Set start)

                // *** End programmer edit section *** (Оборудование.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Оборудование.Название Set end)

                // *** End programmer edit section *** (Оборудование.Название Set end)
            }
        }
        
        /// <summary>
        /// Паспорт.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Паспорт CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Паспорт CustomAttributes)
        [StrLen(255)]
        public virtual string Паспорт
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Паспорт Get start)

                // *** End programmer edit section *** (Оборудование.Паспорт Get start)
                string result = this.fПаспорт;
                // *** Start programmer edit section *** (Оборудование.Паспорт Get end)

                // *** End programmer edit section *** (Оборудование.Паспорт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Паспорт Set start)

                // *** End programmer edit section *** (Оборудование.Паспорт Set start)
                this.fПаспорт = value;
                // *** Start programmer edit section *** (Оборудование.Паспорт Set end)

                // *** End programmer edit section *** (Оборудование.Паспорт Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Тип CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Тип CustomAttributes)
        public virtual IIS.QualityControl.ТипУстройства Тип
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Тип Get start)

                // *** End programmer edit section *** (Оборудование.Тип Get start)
                IIS.QualityControl.ТипУстройства result = this.fТип;
                // *** Start programmer edit section *** (Оборудование.Тип Get end)

                // *** End programmer edit section *** (Оборудование.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Тип Set start)

                // *** End programmer edit section *** (Оборудование.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Оборудование.Тип Set end)

                // *** End programmer edit section *** (Оборудование.Тип Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОборудованиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОборудованиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОборудованиеE", typeof(IIS.QualityControl.Оборудование));
                }
            }
            
            /// <summary>
            /// "ОборудованиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОборудованиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОборудованиеL", typeof(IIS.QualityControl.Оборудование));
                }
            }
        }
    }
}
