//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.QualityControl
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проверяемое.
    /// </summary>
    // *** Start programmer edit section *** (Проверяемое CustomAttributes)

    // *** End programmer edit section *** (Проверяемое CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Проверяемое : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.QualityControl.Качество fКачество;
        
        private IIS.QualityControl.Продукция fПродукция;
        
        private IIS.QualityControl.Отчет fОтчет;
        
        // *** Start programmer edit section *** (Проверяемое CustomMembers)

        // *** End programmer edit section *** (Проверяемое CustomMembers)

        
        /// <summary>
        /// Качество.
        /// </summary>
        // *** Start programmer edit section *** (Проверяемое.Качество CustomAttributes)

        // *** End programmer edit section *** (Проверяемое.Качество CustomAttributes)
        public virtual IIS.QualityControl.Качество Качество
        {
            get
            {
                // *** Start programmer edit section *** (Проверяемое.Качество Get start)

                // *** End programmer edit section *** (Проверяемое.Качество Get start)
                IIS.QualityControl.Качество result = this.fКачество;
                // *** Start programmer edit section *** (Проверяемое.Качество Get end)

                // *** End programmer edit section *** (Проверяемое.Качество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверяемое.Качество Set start)

                // *** End programmer edit section *** (Проверяемое.Качество Set start)
                this.fКачество = value;
                // *** Start programmer edit section *** (Проверяемое.Качество Set end)

                // *** End programmer edit section *** (Проверяемое.Качество Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Проверяемое.Количество CustomAttributes)

        // *** End programmer edit section *** (Проверяемое.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Проверяемое.Количество Get start)

                // *** End programmer edit section *** (Проверяемое.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Проверяемое.Количество Get end)

                // *** End programmer edit section *** (Проверяемое.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверяемое.Количество Set start)

                // *** End programmer edit section *** (Проверяемое.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Проверяемое.Количество Set end)

                // *** End programmer edit section *** (Проверяемое.Количество Set end)
            }
        }
        
        /// <summary>
        /// Проверяемое.
        /// </summary>
        // *** Start programmer edit section *** (Проверяемое.Продукция CustomAttributes)

        // *** End programmer edit section *** (Проверяемое.Продукция CustomAttributes)
        [PropertyStorage(new string[] {
                "Продукция"})]
        [NotNull()]
        public virtual IIS.QualityControl.Продукция Продукция
        {
            get
            {
                // *** Start programmer edit section *** (Проверяемое.Продукция Get start)

                // *** End programmer edit section *** (Проверяемое.Продукция Get start)
                IIS.QualityControl.Продукция result = this.fПродукция;
                // *** Start programmer edit section *** (Проверяемое.Продукция Get end)

                // *** End programmer edit section *** (Проверяемое.Продукция Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверяемое.Продукция Set start)

                // *** End programmer edit section *** (Проверяемое.Продукция Set start)
                this.fПродукция = value;
                // *** Start programmer edit section *** (Проверяемое.Продукция Set end)

                // *** End programmer edit section *** (Проверяемое.Продукция Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.QualityControl.Отчет.
        /// </summary>
        // *** Start programmer edit section *** (Проверяемое.Отчет CustomAttributes)

        // *** End programmer edit section *** (Проверяемое.Отчет CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Отчет"})]
        public virtual IIS.QualityControl.Отчет Отчет
        {
            get
            {
                // *** Start programmer edit section *** (Проверяемое.Отчет Get start)

                // *** End programmer edit section *** (Проверяемое.Отчет Get start)
                IIS.QualityControl.Отчет result = this.fОтчет;
                // *** Start programmer edit section *** (Проверяемое.Отчет Get end)

                // *** End programmer edit section *** (Проверяемое.Отчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверяемое.Отчет Set start)

                // *** End programmer edit section *** (Проверяемое.Отчет Set start)
                this.fОтчет = value;
                // *** Start programmer edit section *** (Проверяемое.Отчет Set end)

                // *** End programmer edit section *** (Проверяемое.Отчет Set end)
            }
        }
    }
    
    /// <summary>
    /// Detail array of Проверяемое.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПроверяемое CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПроверяемое CustomAttributes)
    public class DetailArrayOfПроверяемое : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.QualityControl.DetailArrayOfПроверяемое members)

        // *** End programmer edit section *** (IIS.QualityControl.DetailArrayOfПроверяемое members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Проверяемое by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Проверяемое.
        /// </summary>
        public DetailArrayOfПроверяемое(IIS.QualityControl.Отчет fОтчет) : 
                base(typeof(Проверяемое), ((ICSSoft.STORMNET.DataObject)(fОтчет)))
        {
        }
        
        public IIS.QualityControl.Проверяемое this[int index]
        {
            get
            {
                return ((IIS.QualityControl.Проверяемое)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.QualityControl.Проверяемое dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
